;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-semi&comma
        delete-window
        dired-next-line
        dired-previous-line
        dired-toggle-read-only
        end-of-visual-line
        hippie-expand-no-case-fold
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-kill
        paredit-newline
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        dabbrev-expand
        dired-toggle-marks
        evil-ex
        evil-normal-state
        shrink-window-if-larger-than-buffer
        smex
        text-scale-adjust
        ))
